# LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/wingspan
spring.datasource.username=postgres
spring.datasource.password=Bananafish2!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#file.upload-dir=https://wingspan.sfo3.digitialoceanspaces.com/
# DigitalOcean Spaces Configuration
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=s6USsuLThTcgXSFqhzLl9+FVbkASpCTuGERPKLjfbgM
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=https://sfo3.digitaloceanspaces.com
# Force path-style to prevent bucket name being prepended to the URL
spring.cloud.aws.s3.path-style-access-enabled=true
digitalocean.bucket.name=wingspan
server.port=8080
# Security settings
# spring.security.user.name=admin
# spring.security.user.password=admin123