# LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/wingspan
spring.datasource.username=wadmin
spring.datasource.password=obama
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#file.upload-dir=https://wingspan.sfo3.digitialoceanspaces.com/
# DigitalOcean Spaces Configuration
cloud.aws.credentials.access-key=key-1771880955974
cloud.aws.credentials.secret-key=s6USsuLThTcgXSFqhzLl9+FVbkASpCTuGERPKLjfbgM
cloud.aws.region.static=wingspan.sfo3
cloud.aws.endpoint.uri=https://wingspan.sfo3.digitialoceanspaces.com/
digitalocean.bucket.name=wingspan
server.port=8080
# Security settings
# spring.security.user.name=admin
# spring.security.user.password=admin123